---
layout: post
title: Testing for exceptions in JUnit revised
date: '2010-09-25T21:13:00.004+02:00'
author: Tomasz Nurkiewicz
tags:
- testing
- aop
- design patterns
- tdd
- junit
modified_time: '2011-11-17T18:41:49.774+01:00'
blogger_id: tag:blogger.com,1999:blog-6753769565491687768.post-913626062211997442
blogger_orig_url: https://www.nurkiewicz.com/2010/09/testing-for-exceptions-in-junit-revised.html
---

In his recent <a href="http://monkeyisland.pl/2010/07/26/expected-exception-in-tests">post</a> the author of fantastic mocking framework <a href="http://mockito.org/">Mockito</a> collected few rules about testing exceptions. What caught my attention is the advice to use JUnit rules (<i>nomen est omen</i>!) for testing exceptions. <a href="http://kentbeck.github.com/junit/javadoc/latest/org/junit/rules/ExpectedException.html">ExpectedException</a> rule gathers advantages of both <span style="font-family: &quot;Courier New&quot;, &quot;Courier&quot;, monospace;">expected</span> <span style="font-family: &quot;;">@Test</span> attribute clarity  and <span style="font-family: &quot;;">try-catch</span> strictness. Here is the example:<br /><br /><pre class="brush: java"><br />public class DefaultFooServiceTest {<br /><br /> private FooService fooService = new DefaultFooService();<br /><br /> @Rule<br /> public ExpectedException exception = new ExpectedException();<br /><br /> @Test<br /> public void shouldThrowNpeWhenNullName() throws Exception {<br />  //given<br />  String name = null;<br /><br />  //when<br />  exception.expect(NullPointerException.class);<br />  fooService.echo(name);<br /><br />  //then<br /> }<br /><br />}<br /></pre><br /><br />Szczepan claims that <span style="font-family: &quot;Courier New&quot;, &quot;Courier&quot;, monospace;">ExpectedException</span> fits into <i>given/when/then</i> test template nicely. I disagree! Look at the code snippet above – what is the most natural place to put assertions on exception being thrown? From the obvious reasons it must be the last line before the line that actually throws the exceptions. So you have a choice to put assertion as the last statement in <i>given</i> block or as first in <i>when</i> block. You are right, this is how this test should look like in an ideal world:<br /><br /><pre class="brush: java"><br />@Test<br />public void shouldThrowNpeWhenNullName() throws Exception {<br /> //given<br /> String name = null;<br /><br /> //when<br /> fooService.echo(name);<br /><br /> //then<br /> exception.expect(NullPointerException.class);<br />}<br /><br /></pre><br /><br /><br /><a name='more'></a>No we’re talking! There’s just this tiny problem with example above – we expect code in <i>when</i> block to throw an exception and put assertions afterwards in <i>then</i> block. See the problem? If we could somehow transparently catch the exception, store it somewhere, return normally and let assertions to run against it... With AOP it is actually pretty easy, but I wanted to implement this feature using pure Java and with JUnit framework. First, I will introduce <span style="font-family: &quot;;">@UnderTest</span> marker annotation:<br /><br /><pre class="brush: java"><br />@Retention(RetentionPolicy.RUNTIME)<br />@Target(ElementType.FIELD)<br />public @interface UnderTest {<br />}<br /></pre><br /><br />Now put this annotation above the field in your test case corresponding to class under test:<br /><br /><br /><pre class="brush: java"><br />@UnderTest<br />private FooService fooService = new DefaultFooService();<br /></pre><br /><br />Although the annotation brings some value itself, marking which object is actually being tested, it is not meant for documentation and test readability, I am going to use it together with some Java reflection. I mentioned that AOP would solve our problems. JUnit 4.7 ships with AOP-like mechanism called <a href="http://kentbeck.github.com/junit/javadoc/latest/org/junit/rules/MethodRule.html">rules</a>. By writing a rule (<span style="font-family: &quot;;">ExpectedException</span> is an example of a JUnit built-in rule) you simply create an interceptor around every test method. With this interceptor you can, for instance, run test method in separate thread, do some setup and cleanup, etc. My custom rule will do two things:<br /><br /><ul><li>wrap class under test in Java proxy to catch every exception, store it and return normally</li><li>verify thrown exception against assertions introduced in <i>then</i> block</li></ul><br />Skeleton of the rule code is as follows:<br /><br /><pre class="brush: java"><br />package com.blogspot.nurkiewicz.junit.exceptionassert;<br /><br />public class ExceptionAssert implements MethodRule {<br /><br /> @Override<br /> public Statement apply(Statement base, FrameworkMethod method, Object testCase) {<br />  this.testCase = testCase;<br />  return new ExceptionAssertStatement(base);<br /> }<br /><br /> private class ExceptionAssertStatement extends Statement {<br /><br />  private final Statement base;<br /><br />  private Throwable exceptionThrownFromClassUnderTest;<br />  private Field underTestField;<br /><br />  public ExceptionAssertStatement(Statement base) {<br />   this.base = base;<br />   underTestField = findClassUnderTestField(testCase);<br />  }<br /><br />  @Override<br />  public void evaluate() throws Throwable {<br />   final Object originalClassUnderTest = wrapClassUnderTest(testCase);<br />   try {<br />    base.evaluate();<br />   } finally {<br />    setUnderTestField(originalClassUnderTest);<br />   }<br />   verifyException();<br />  }<br /><br />}<br /><br /></pre><br /><br /><span style="font-family: &quot;;">ExceptionAssertStatement</span> is an example of <a href="http://en.wikipedia.org/wiki/Decorator_pattern">Decorator</a> pattern: it takes original <span style="font-family: &quot;;">Statement</span> instance (representing test method execution) and replaces it with wrapped  (decorated) custom class, also implementing <span style="font-family: &quot;;">Statement</span>. <span style="font-family: &quot;;">ExceptionAssertStatement</span> adds some additional logic and calls original’s statement <span style="font-family: &quot;;">evaluate()</span> method. This additional logic is pretty straightforward:<br /><ul><li>first, take class under test and wrap it (wrapping again!) in a proxy</li><li>execute the test method (evaluate())</li><li>(revert to original class under test)</li><li>when test method exits, verify exception throw from class under test (if any)</li></ul><br />The last interesting piece is the proxy wrapping class under test itself:<br /><br /><pre class="brush: java"><br />private Object wrapWithProxy(final Object classUnderTest) {<br /> return Proxy.newProxyInstance(classUnderTest.getClass().getClassLoader(), new Class[]{underTestField.getType()}, new InvocationHandler() {<br />  @Override<br />  public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {<br />   try {<br />    return method.invoke(classUnderTest, args);<br />   } catch (InvocationTargetException e) {<br />    exceptionThrownFromClassUnderTest = e.getCause();<br />    return null;<br />   }<br />  }<br /> });<br />}<br /><br /></pre><br /><br />Nothing fancy: if class under test throws an exception, store it somewhere and return normally. Not that hard. Enough of the internals, let’s look at our brand new rule in action:<br /><br /><pre class="brush: java"><br />public class DefaultFooServiceTest {<br /><br /> @UnderTest<br /> private FooService fooService = new DefaultFooService();<br /><br /> @Rule<br /> public ExceptionAssert exception = new ExceptionAssert();<br /><br /> @Test<br /> public void shouldReturnHelloString() throws Exception {<br />  //given<br />  String name = "Tomek";<br /><br />  //when<br />  final String result = fooService.echo(name);<br /><br />  //then<br />  assertEquals("Hello, Tomek!", result);<br /> }<br /><br /> @Test<br /> public void shouldThrowNpeWhenNullName() throws Exception {<br />  //given<br />  String name = null;<br /><br />  //when<br />  fooService.echo(name);<br /><br />  //then<br />  exception.expect(NullPointerException.class);<br /> }<br /><br /> @Test<br /> public void shouldThrowIllegalArgumentWhenNameJohn() throws Exception {<br />  //given<br />  String name = "John";<br /><br />  //when<br />  fooService.echo(name);<br /><br />  //then<br />  exception.expect(IllegalArgumentException.class)<br />    .expectMessage("Name: 'John' is not allowed");<br /> }<br /><br />}<br /><br /></pre><br /><br />First test method does not expect any exception to be thrown – it if will, test will fail. Second test expects <span style="font-family: &quot;;">NullPointerException</span>. Please note that if the exception will be thrown from any other line than <span style="font-family: &quot;;">fooService.echo()</span> (or <span style="font-family: &quot;;">fooService.echo()</span> won’t throw <span style="font-family: &quot;;">NullPointerException</span>), test will fail. The last test shows that you can also assert exception message as well.<br /><br />Few things are still missing in <a href="http://github.com/nurkiewicz/junit-exception-assert-rule/downloads">0.0.1</a> "version", mainly proxying classes (CGLIB, anyone?); also, some syntactic sugar together with DSL-like (<a href="http://code.google.com/p/fest">FEST</a>-like) assertions could be introduced:<br /><br /><pre class="brush: java"><br />@Test<br />public void shouldThrowIllegalArgumentWhenNameJohn() throws Exception {<br /> //given<br /> String name = "John";<br /><br /> //when<br /> fooService.echo(name);<br /><br /> //then<br /> expect(IllegalArgumentException.class)<br />   .withMessage("Name: 'John' is not allowed");<br />}<br /><br /></pre><br /><br />Also I had to copy&amp;paste big parts of JUnit’s <span style="font-family: &quot;;">ExpectedException</span>, as most obvious inheritance was not possible due to private constructor. But still, take a look at <span style="font-family: &quot;;">ExceptionAssert</span> rule and see for yourself how readable exception testing can be. As always, source code can be cloned and downloaded from my GitHub <a href="http://github.com/nurkiewicz/junit-exception-assert-rule">account</a>. Any comments and contributions are welcome!